// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c26b5689-620f-4721-86ef-9bac1c88275b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tE9LfOdQJ",
    "aws_user_pools_web_client_id": "6f3gd4dvst0mamqv490be7ed13",
    "aws_appsync_graphqlEndpoint": "https://3kh4pfeaxbgrbeybeaqoghcaqy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
